rem *** tests ***
md tests
call gen-input-via-stdout.bat "exec\tmp.exe 3" "tests/01.in" 1
call gen-input-via-stdout.bat "exec\tmp.exe 4" "tests/02.in" 2
call gen-input-via-stdout.bat "exec\tmp.exe 5" "tests/03.in" 3
call gen-input-via-stdout.bat "exec\tmp.exe 6" "tests/04.in" 4
call gen-input-via-stdout.bat "exec\tmp.exe 7" "tests/05.in" 5
call gen-input-via-stdout.bat "exec\tmp.exe 50" "tests/06.in" 6
call gen-input-via-stdout.bat "exec\tmp.exe 49" "tests/07.in" 7
call gen-input-via-stdout.bat "exec\tmp.exe 48" "tests/08.in" 8
call gen-input-via-stdout.bat "exec\tmp.exe 47" "tests/09.in" 9
call gen-input-via-stdout.bat "exec\tmp.exe 100" "tests/10.in" 10
call gen-input-via-stdout.bat "exec\tmp.exe 99" "tests/11.in" 11
call gen-input-via-stdout.bat "exec\tmp.exe 98" "tests/12.in" 12
call gen-input-via-stdout.bat "exec\tmp.exe 97" "tests/13.in" 13
call gen-input-via-stdout.bat "exec\tmp.exe 976" "tests/14.in" 14
call gen-input-via-stdout.bat "exec\tmp.exe 975" "tests/15.in" 15
call gen-input-via-stdout.bat "exec\tmp.exe 974" "tests/16.in" 16
call gen-input-via-stdout.bat "exec\tmp.exe 973" "tests/17.in" 17
call gen-input-via-stdout.bat "exec\tmp.exe 1000" "tests/18.in" 18
call gen-input-via-stdout.bat "exec\tmp.exe 3000" "tests/19.in" 19
call gen-input-via-stdout.bat "exec\tmp.exe 2999" "tests/20.in" 20
call gen-input-via-stdout.bat "exec\tmp.exe 2998" "tests/21.in" 21
call gen-input-via-stdout.bat "exec\tmp.exe 2997" "tests/22.in" 22
call gen-input-via-stdout.bat "exec\tmp.exe 2996" "tests/23.in" 23
call gen-input-via-stdout.bat "exec\tmp.exe 2995" "tests/24.in" 24
call gen-input-via-stdout.bat "exec\tmp.exe 2994" "tests/25.in" 25
call gen-input-via-stdout.bat "exec\tmp.exe 2993" "tests/26.in" 26
call gen-input-via-stdout.bat "exec\tmp.exe 2992" "tests/27.in" 27
call gen-input-via-stdout.bat "exec\tmp.exe 2991" "tests/28.in" 28
call gen-input-via-stdout.bat "exec\tmp.exe 2990" "tests/29.in" 29
call gen-input-via-stdout.bat "exec\tmp.exe 2689" "tests/30.in" 30
call gen-input-via-stdout.bat "exec\tmp.exe 3" "tests/01.out" 1
call gen-input-via-stdout.bat "exec\tmp.exe 4" "tests/02.out" 2
call gen-input-via-stdout.bat "exec\tmp.exe 5" "tests/03.out" 3
call gen-input-via-stdout.bat "exec\tmp.exe 6" "tests/04.out" 4
call gen-input-via-stdout.bat "exec\tmp.exe 7" "tests/05.out" 5
call gen-input-via-stdout.bat "exec\tmp.exe 50" "tests/06.out" 6
call gen-input-via-stdout.bat "exec\tmp.exe 49" "tests/07.out" 7
call gen-input-via-stdout.bat "exec\tmp.exe 48" "tests/08.out" 8
call gen-input-via-stdout.bat "exec\tmp.exe 47" "tests/09.out" 9
call gen-input-via-stdout.bat "exec\tmp.exe 100" "tests/10.out" 10
call gen-input-via-stdout.bat "exec\tmp.exe 99" "tests/11.out" 11
call gen-input-via-stdout.bat "exec\tmp.exe 98" "tests/12.out" 12
call gen-input-via-stdout.bat "exec\tmp.exe 97" "tests/13.out" 13
call gen-input-via-stdout.bat "exec\tmp.exe 976" "tests/14.out" 14
call gen-input-via-stdout.bat "exec\tmp.exe 975" "tests/15.out" 15
call gen-input-via-stdout.bat "exec\tmp.exe 974" "tests/16.out" 16
call gen-input-via-stdout.bat "exec\tmp.exe 973" "tests/17.out" 17
call gen-input-via-stdout.bat "exec\tmp.exe 1000" "tests/18.out" 18
call gen-input-via-stdout.bat "exec\tmp.exe 3000" "tests/19.out" 19
call gen-input-via-stdout.bat "exec\tmp.exe 2999" "tests/20.out" 20
call gen-input-via-stdout.bat "exec\tmp.exe 2998" "tests/21.out" 21
call gen-input-via-stdout.bat "exec\tmp.exe 2997" "tests/22.out" 22
call gen-input-via-stdout.bat "exec\tmp.exe 2996" "tests/23.out" 23
call gen-input-via-stdout.bat "exec\tmp.exe 2995" "tests/24.out" 24
call gen-input-via-stdout.bat "exec\tmp.exe 2994" "tests/25.out" 25
call gen-input-via-stdout.bat "exec\tmp.exe 2993" "tests/26.out" 26
call gen-input-via-stdout.bat "exec\tmp.exe 2992" "tests/27.out" 27
call gen-input-via-stdout.bat "exec\tmp.exe 2991" "tests/28.out" 28
call gen-input-via-stdout.bat "exec\tmp.exe 2990" "tests/29.out" 29
call gen-input-via-stdout.bat "exec\tmp.exe 2689" "tests/30.out" 30
